upd main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: Build and Deploy DataGateVPNBot
+name: Build and Deploy DataGateVPNBot main
 
 on:
   push:
@@ -7,22 +7,40 @@ on:
 
 jobs:
   build-and-deploy:
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
+    name: Build and Deploy on Raspberry Pi
+    env:
+      ASPNETCORE_ENVIRONMENT: Production
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-    - name: Setup .NET 8
-      uses: actions/setup-dotnet@v3
-      with:
-        dotnet-version: 8.0.x
+      - name: Use existing configuration files
+        run: |
+          cp /home/rackot/configs/appsettings.json ./appsettings.json
+          cp /home/rackot/configs/appsettings.Development.json ./appsettings.Development.json
+          
+          cp /home/rackot/certs/datagatetgbot.pem ./datagatetgbot.pem
+          cp /home/rackot/certs/datagatetgbot.key ./datagatetgbot.key
+          
+          cp /home/rackot/Photo/bot.gif ./bot.gif
 
-    - name: Restore dependencies
-      run: dotnet restore ./DataGateVPNBotV1.csproj
+      - name: Verify files
+        run: |
+          echo "Verifying required files..."
+          for file in appsettings.json appsettings.Development.json datagatetgbot.pem datagatetgbot.key bot.gif; do
+            if [ -s ./$file ]; then
+              echo "$file is present and not empty.";
+            else
+              echo "$file is missing or empty!";
+              exit 1;
+            fi
+          done
 
-    - name: Build application
-      run: dotnet publish ./DataGateVPNBotV1.csproj -c Release -r linux-arm64 --self-contained true -o ./publish
+      - name: Build Docker image
+        run: |
+          docker build -t datagatevpn-main -f Dockerfile .
 
       - name: Deploy Docker container
         run: |
